{% set name = "gitlab-ci-ls" %}
{% set version = "0.21.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alesbrelih/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 354419ad6b8e3c944970430824e85cb4cef40b537bf6bb13a92016d2a4060494

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/alesbrelih/{{ name }}
  license: MIT
  license_file:
    - vscode-extension/LICENSE.txt
    - THIRDPARTY.yml
  summary: Language server for GitLab CI
  dev_url: https://github.com/alesbrelih/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
