{% set name = "gitlab-ci-ls" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alesbrelih/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 95dec4bdcdc9a22822bb4a6e96de6ac0117172b5c81f7e945278d947b46310ef

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl
  run:
    - openssl

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/alesbrelih/{{ name }}
  license: MIT
  license_file:
    - vscode-extension/LICENSE.txt
    - THIRDPARTY.yml
  summary: Language server for GitLab CI
  dev_url: https://github.com/alesbrelih/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
