context:
  version: "1.0.5"

package:
  name: gitlab-ci-ls
  version: ${{ version }}

source:
  url: https://github.com/alesbrelih/gitlab-ci-ls/archive/${{ version }}.tar.gz
  sha256: 7789bc4d91e9c179b1334b963101837b34515bd1146503bca719dc0cdf294886

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gitlab-ci-ls --help

about:
  license: MIT
  license_file:
    - vscode-extension/LICENSE.txt
    - THIRDPARTY.yml
  summary: Language server for GitLab CI
  homepage: https://github.com/alesbrelih/gitlab-ci-ls
  repository: https://github.com/alesbrelih/gitlab-ci-ls

extra:
  recipe-maintainers:
    - danielnachun
