context:
  version: "1.0.0"

package:
  name: gitlab-ci-ls
  version: ${{ version }}

source:
  url: https://github.com/alesbrelih/gitlab-ci-ls/archive/${{ version }}.tar.gz
  sha256: 6feed3501591cf39b7e4c35b0a7c9fec4eba129ac248a69257c02dacc266eddc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gitlab-ci-ls --help

about:
  license: MIT
  license_file:
    - vscode-extension/LICENSE.txt
    - THIRDPARTY.yml
  summary: Language server for GitLab CI
  homepage: https://github.com/alesbrelih/gitlab-ci-ls
  repository: https://github.com/alesbrelih/gitlab-ci-ls

extra:
  recipe-maintainers:
    - danielnachun
