context:
  version: "1.4.0"

package:
  name: gitlab-ci-ls
  version: ${{ version }}

source:
  url: https://github.com/alesbrelih/gitlab-ci-ls/archive/${{ version }}.tar.gz
  sha256: 5542e69da2ef3ba10abd362f3aa7c3ceb144bc4ba1f6809fa933b2636f95a4c5

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gitlab-ci-ls --help

about:
  license: MIT
  license_file:
    - vscode-extension/LICENSE.txt
    - THIRDPARTY.yml
  summary: Language server for GitLab CI
  homepage: https://github.com/alesbrelih/gitlab-ci-ls
  repository: https://github.com/alesbrelih/gitlab-ci-ls

extra:
  recipe-maintainers:
    - danielnachun
