context:
  version: "1.3.4"

package:
  name: gitlab-ci-ls
  version: ${{ version }}

source:
  url: https://github.com/alesbrelih/gitlab-ci-ls/archive/${{ version }}.tar.gz
  sha256: 22c681b9f9f19bf7bcf2269a849e0d8be42cba0c7a55bfab724d54d6cfa054e6

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - gitlab-ci-ls --help

about:
  license: MIT
  license_file:
    - vscode-extension/LICENSE.txt
    - THIRDPARTY.yml
  summary: Language server for GitLab CI
  homepage: https://github.com/alesbrelih/gitlab-ci-ls
  repository: https://github.com/alesbrelih/gitlab-ci-ls

extra:
  recipe-maintainers:
    - danielnachun
